apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: news
spec:
  selector:
    matchLabels:
      app: spring-test-app
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: news
    spec:
      containers:
        - name: news
          image: owaiskhan02/webapplication:news # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081 # The port that the container is running on in the cluster